# Generated by Django 2.2.6 on 2020-05-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('thumbURL', models.URLField()),
            ],
        ),
    ]
