# Generated by Django 2.2.6 on 2020-06-14 03:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Drink', 'verbose_name_plural': 'Drinks'},
        ),
        migrations.AlterModelOptions(
            name='drinkslim',
            options={'verbose_name': 'DrinkSlim', 'verbose_name_plural': 'DrinkSlims'},
        ),
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drinkslim',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='drink',
            table='drink',
        ),
        migrations.AlterModelTable(
            name='drinkslim',
            table='drink_slim',
        ),
    ]
